# Generated by Django 3.0.7 on 2020-06-28 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
