# Generated by Django 3.0.7 on 2020-06-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200628_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
